import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header'
import { Posts } from 'src/components/Posts'
import { useEffect,useState,useCallback } from 'react'

const Home=() =>{



  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>

      <Posts/>

    </div>
  )
}

export default Home;
